fix: Escape group names when calling keycloak
IBM/iam-to-keycloak-migration pull request #3
Opened 2024-11-29 13:49 UTC by tom-youd

As per title - otherwise groups such as `Devops engineers (test)` fails when calling keycloak

2024-12-02 13:22 UTC, Jamstah commented
This might be easier (and more reliable) with curl, as we rely on curl being present anyway:

```
jammy@mac007470 ~ % curl --get http://example.org/search --data-urlencode "search=My Group Name (With para)" -v
* Host example.org:80 was resolved.
* IPv6: 2606:2800:21f:cb07:6820:80da:af6b:8b2c
* IPv4: 93.184.215.14
*   Trying [2606:2800:21f:cb07:6820:80da:af6b:8b2c]:80...
* Connected to example.org (2606:2800:21f:cb07:6820:80da:af6b:8b2c) port 80
> GET /search?search=My+Group+Name+%28With+para%29 HTTP/1.1
> Host: example.org
> User-Agent: curl/8.7.1
> Accept: */*
```

2024-12-02 13:26 UTC, Jamstah commented
Also, don't we have the same problem with [getMembersFromGroup](https://github.com/IBM/iam-to-keycloak-migration/blob/2b129e01e7ec93d5574ac04c2add99df24129354/iam-keycloak-migration.sh#L424)?

```
keycloakGroupMembers="$(curl -ks "https://$keycloakUrl/admin/realms/$keycloakCloudPakRealm/groups/$1/members" \
  --header "Authorization: Bearer $keycloakAccessToken")"
```

Or does curl do something clever for us there?

2024-12-02 14:43 UTC, tom-youd commented
> This might be easier (and more reliable) with curl, as we rely on curl being present anyway:
> 
> ```
> jammy@mac007470 ~ % curl --get http://example.org/search --data-urlencode "search=My Group Name (With para)" -v
> * Host example.org:80 was resolved.
> * IPv6: 2606:2800:21f:cb07:6820:80da:af6b:8b2c
> * IPv4: 93.184.215.14
> *   Trying [2606:2800:21f:cb07:6820:80da:af6b:8b2c]:80...
> * Connected to example.org (2606:2800:21f:cb07:6820:80da:af6b:8b2c) port 80
> > GET /search?search=My+Group+Name+%28With+para%29 HTTP/1.1
> > Host: example.org
> > User-Agent: curl/8.7.1
> > Accept: */*
> ```

Interesting, I tried that with the customer and it still wasn't working. I'll have a look again after the release

2024-12-11 10:48 UTC, tom-youd commented
Ok so figured out why it didn't work with the client... we didn't have `--get` which meant the query string was need getting added to the request.

>Also, don't we have the same problem with [getMembersFromGroup](https://github.com/IBM/iam-to-keycloak-migration/blob/2b129e01e7ec93d5574ac04c2add99df24129354/iam-keycloak-migration.sh#L424)?

No that is a unique id so that is fine :)

2024-12-20 15:26 UTC, merged

2024-12-20 15:43 UTC, Jamstah requested changes

2024-12-20 15:43 UTC, Jamstah commented on iam-keycloak-migration.sh
> +  keycloakGroups="$(curl -ks --get "https://$keycloakUrl/admin/realms/$keycloakCloudPakRealm/groups" --data-urlencode "search=$1&exact=true" \
Isn't this going to also encode the & separating the parameters?

I think we need two --data-urlencode flags

2024-12-20 15:43 UTC, Jamstah commented on iam-keycloak-migration.sh
> +  keycloakGroups="$(curl -ks --get "https://$keycloakUrl/admin/realms/$keycloakCloudPakRealm/groups" --data-urlencode "search=$1&exact=true" \
Sorry Tom, this comment was in a pending review, forgot to hit the submit review button!